packages:
  - website
  - packages/*

allowBuilds:
  '@swc/core': true
  esbuild: true

patchedDependencies:
  '@tanstack/start-static-server-functions': patches/@tanstack__start-static-server-functions.patch

publicHoistPattern:
  - nitro-nightly
