packages:
  - website

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

patchedDependencies:
  '@tanstack/start-static-server-functions': patches/@tanstack__start-static-server-functions.patch

publicHoistPattern:
  - nitro-nightly
