/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ClimbingImport } from './routes/climbing'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ClimbingRoute = ClimbingImport.update({
  id: '/climbing',
  path: '/climbing',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/climbing': {
      id: '/climbing'
      path: '/climbing'
      fullPath: '/climbing'
      preLoaderRoute: typeof ClimbingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/climbing': typeof ClimbingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/climbing': typeof ClimbingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/climbing': typeof ClimbingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/climbing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/climbing'
  id: '__root__' | '/' | '/climbing'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClimbingRoute: typeof ClimbingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClimbingRoute: ClimbingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/climbing"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/climbing": {
      "filePath": "climbing.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
