name: Fetch ascents

on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * 1,3
    - cron: 0 17 * * 6

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Fetch ascents
        run: |
          printf '%s' '${{ secrets.TOKEN_JSON }}' > token.json

          node --experimental-strip-types main.ts

      #- name: Update secret
      #  env:
      #    GH_TOKEN: ${{ github.token }}
      #  run: |
      #    gh secret set TOKEN_JSON < token.json

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          # this email is a special GitHub email which associates the github-actions[bot] user with the commits
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data
          git diff-index --cached --quiet HEAD || git commit -m "data update $(date +%F)"

          for i in $(seq 1 50); do
            # sleep 1 second after the first attempt (i > 1)
            [ $i -gt 1 ] && sleep 1;
            # s stores the exit code of the pull/push
            # if successfully pushed, set s=0 and break the loop
            # otherwise save the exit code  of pull/push to s
            (git pull --rebase && git push) && s=0 && break || s=$?;
          done
          # exit with the same exit code as pull/push to propagate the error
          exit $s
